#!/usr/bin/bash
print(){
	echo -e "  ✅ "$1
}
sudo -v
echo "  Iniciando actualización"
sudo apt update
print "Paquetes actualizados"
print "Instalando actualizaciones"
sudo apt upgrade -y
print "Removiendo paquetes innecesarios"
sudo apt autoremove -y
print "Limpiando archivos residuales"
sudo apt autoclean -y


